# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\rStatusRequest\x12\n\n\x02id\x18\x01 \x01(\t\" \n\x0eStatusResponse\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\"#\n\x14MetricsStatusRequest\x12\x0b\n\x03\x65nv\x18\x01 \x01(\t\"A\n\x15MetricsStatusResponse\x12(\n\x07metrics\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2\xaa\x01\n\x07Greeter\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12\x32\n\x0fGetServerStatus\x12\x0e.StatusRequest\x1a\x0f.StatusResponse\x12\x41\n\x10GetMetricsStatus\x12\x15.MetricsStatusRequest\x1a\x16.MetricsStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=47
  _globals['_HELLOREQUEST']._serialized_end=75
  _globals['_HELLOREPLY']._serialized_start=77
  _globals['_HELLOREPLY']._serialized_end=106
  _globals['_STATUSREQUEST']._serialized_start=108
  _globals['_STATUSREQUEST']._serialized_end=135
  _globals['_STATUSRESPONSE']._serialized_start=137
  _globals['_STATUSRESPONSE']._serialized_end=169
  _globals['_METRICSSTATUSREQUEST']._serialized_start=171
  _globals['_METRICSSTATUSREQUEST']._serialized_end=206
  _globals['_METRICSSTATUSRESPONSE']._serialized_start=208
  _globals['_METRICSSTATUSRESPONSE']._serialized_end=273
  _globals['_GREETER']._serialized_start=276
  _globals['_GREETER']._serialized_end=446
# @@protoc_insertion_point(module_scope)
